// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4O9qmMC8GjrHIBIRq8tRHI9XmgnnHxE8',
    appId: '1:251802356530:android:6e9b4479719719ba57252b',
    messagingSenderId: '251802356530',
    projectId: 'nucleus-ef2d2',
    storageBucket: 'nucleus-ef2d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjJGsPyq5hpiYR0xpbXXsfe9_ieOMO2Rc',
    appId: '1:251802356530:ios:832e907e9cba787757252b',
    messagingSenderId: '251802356530',
    projectId: 'nucleus-ef2d2',
    storageBucket: 'nucleus-ef2d2.firebasestorage.app',
    iosBundleId: 'com.example.nucleus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjJGsPyq5hpiYR0xpbXXsfe9_ieOMO2Rc',
    appId: '1:251802356530:ios:832e907e9cba787757252b',
    messagingSenderId: '251802356530',
    projectId: 'nucleus-ef2d2',
    storageBucket: 'nucleus-ef2d2.firebasestorage.app',
    iosBundleId: 'com.example.nucleus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfNTbSjllbQRDtxP1A-IqZSQCXcoU8iYo',
    appId: '1:251802356530:web:7cbb8770bc7e495d57252b',
    messagingSenderId: '251802356530',
    projectId: 'nucleus-ef2d2',
    authDomain: 'nucleus-ef2d2.firebaseapp.com',
    storageBucket: 'nucleus-ef2d2.firebasestorage.app',
    measurementId: 'G-8XD9PWF517',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfNTbSjllbQRDtxP1A-IqZSQCXcoU8iYo',
    appId: '1:251802356530:web:7cbb8770bc7e495d57252b',
    messagingSenderId: '251802356530',
    projectId: 'nucleus-ef2d2',
    authDomain: 'nucleus-ef2d2.firebaseapp.com',
    storageBucket: 'nucleus-ef2d2.firebasestorage.app',
    measurementId: 'G-8XD9PWF517',
  );

}